:datasett: FKB-BygnAnlegg
:publisert: 2026-10-05
:versjon: 5.2
:skjemaversjon: 5.2
:versjon-forrige: 5.1
:versjon-erstattet-av: 5.2
:underversjon: 2027-01-01
:underversjon-forrige: 2024-07-01
:metadata-url: https://kartkatalog.geonorge.no/metadata/fkb-bygnanlegg/ede5ffb2-ee2a-44a3-852d-369a14d97f2e
:dokumentstatus: 2
// All informasjon i hode over denne linja må fylles ut for hvert datasett. 
include::../felles_prodspek/filhode.adoc[]

== Innledning, historikk og endringslogg

=== Innledning

FKB-BygnAnlegg er en del av Felles Kartdatabase (FKB). FKB-spesifikasjonen er en serie produktspesifikasjoner for detaljerte basis geodata som samles inn og forvaltes gjennom Geovekst. Generelle beskrivelser for alle FKB-spesifikasjonene er samlet i {fkbGenerellDel-url}[FKB-Generell del].

FKB-BygnAnlegg beskriver bygningsmessige anlegg som ikke er spesifisert i andre fagspesifikke FKB-datasett som FKB-Bygning eller FKB-Veg. Dette inkluderer objekter som murer, gjerder, kaier, moloer, tanker etc. 

Mye av detaljinformasjonen om registrering av de ulike objekttypene i FKB er samlet i egne Fotogrammetriske registreringsinstrukser. Fotogrammetrisk registreringsinstruks for {datasett} 5.0 finnes på {reginstrbase-url}{datasett}/5.0/Fotogrammetrisk_2024-01-01.

Denne produktspesifikasjonen er utarbeidet iht. SOSI produktspesifikasjoner – Krav og godkjenning 5.0 <<SOSI-KRAV>>. UML-modellen som ligger til grunn for innhold i diagrammene og dokumentasjon i kap. 5, følger reglene i SOSI Regler for UML-modellering, versjon 5.1 <<SOSI-UML>>. http://sosi.geonorge.no/veiledere/UML[Denne veilederen] gir hjelp til å lese UML-diagrammene.


=== Historikk

Tidligere versjoner:

* FKB versjon 3.3 oktober 2001
* FKB versjon 3.4 august 2002
* FKB-BygnAnlegg versjon 4.0 – 2007-01-01
* FKB-BygnAnlegg versjon 4.01 - 2009-03-10 
* FKB-BygnAnlegg versjon 4.01 - 2011-01-01 
* FKB-BygnAnlegg versjon 4.02 - 2011-12-01
* FKB-BygnAnlegg versjon 4.02 - 2013-01-01
* FKB-BygnAnlegg versjon 4.6 – 2016-06-01
* FKB-BygnAnlegg versjon 4.61 – 2018-01-01
* FKB-BygnAnlegg versjon 5.0 - 2022-01-01
* FKB-BygnAnlegg versjon 5.0.1 - 2022-01-01
* FKB-BygnAnlegg versjon 5.0.2 - 2022-01-01
* FKB-BygnAnlegg versjon 5.1 - 2024-07-01


=== Endringslogg

==== Innhold i endringsloggen

FKB 5.0 er en ny hovedversjon av FKB. Dette innebærer at det er gjort større endringer i standarden. Det vil ikke være tilstrekkelig å lese endringsloggen for å få et helhetlig bilde av FKB 5.0 produktspesifikasjonene. For å få et komplett bilde av produktspesifikasjonen må man lese dokumentasjonen som en helhet, inkludert de gjennomgående endringene som er beskrevet i FKB Generell del 5.0 <<FKB>>.

Endringsloggene for det enkelte datasett har som ambisjonsnivå å beskrive de viktigste endringene når det gjelder datainnhold (objekttyper) siden forrige versjon. Endringsloggen vil ikke inneholde alle detaljerte endringer på egenskapsnivå eller endringer når det gjelder utvekslingsformat,  datamodellering eller lignende.

==== Endringer fra FKB-ByngAnlegg 5.1 til FKB-BygnAnlegg 5.2

* Lagt til den opsjonelle egenskapen høydeOverBakken (HOB) på objekttype Gjerde
* Fjernet realisering fra Bygnan 4.0 (SOSI del 2) da denne standarden er tilbaketrukket
* Oppdatert kap. 6 med referanse til Vedlegg B i FKB Generell del

==== Endringer fra FKB-ByngAnlegg 5.0.2 til FKB-BygnAnlegg 5.1

* Lagt til taggen inlineOrByReference=byReference på alle assosiasjoner (gir nytt GML-Schema som sikrer at assosierte objekter utveksles som referanser i GML). 
* Justeringer/forbedringer i dokumentasjonsmal. Dokumentasjon kun tilgjengelig på HTML-format.

==== Endringer fra FKB-BygnAnlegg 5.0.1 til FKB-BygnAnlegg 5.0.2

* Lagt inn manglende tagg defaultCodeSpace på egenskapen medium på FeatureType Parkdetalj] og egenskapen høydereferanse på featuretypen Slipp
* Rettet taggen SOSI_navn på assosiasjon fra Flytebrygge til FlytebryggeLandgang fra FLYTEBRYGGELANGANG til FLYTEBRYGGELANDGANG

==== Endringer fra FKB-ByngAnlegg 5.0 til FKB-BygnAnlegg 5.0.1

* Feilretting: Geometriegenskap for Taubane endret fra GM_Surface til GM_Curve

==== Endringer fra FKB-ByngAnlegg 4.61 til FKB-BygnAnlegg 5.0

* Oppdatert generelle konsepter fra FKB 5.0 generell del <<FKB>>
* Objekttypene Bruavgrensning, BrønnGrense, Tankkant, Tårnkant, SkråForstøtningsmurAvgrensning, Svømmebassengkant, Tribunekant, Damkant, Elveforbygningkant, Elveterkselkant, FiskehjellGrense, Flytebryggekant, Molokant utgår som egne objekttyper. Flate-objekttypene modelleres med heleid flategeometri.
* Innført assosiasjon fra Bru til Brudetalj for å kunne angi hvilke Brudetaljer som tilhører/beskriver hvilke bruer.
* Innført assosiasjon fra Fiskehjell til Fiskehjellmøne for å kunne angi hvilke FiskehjellMøner som tilhører hvilke Fiskehjell.
* Innført objekttype FlytebryggeLandgang og FlytebryggeUtligger. Assosiasjon fra Flytebrygge til FlytebryggeLandgang og FlytebryggeUtligger for å kunne angi hvilke objekter som tilhører hvilke flytebrygger.
* Objekttype Flytebrygge endret fra punkt-, kurve eller flategeometri til påkrevd flategeometri.
* Bensinpumpe, Smørebukk, KloakkrenseanleggGrense, Sandkasse, Fortøyningskar, Fløtningsrenne og Dike/Dikekant utgår
* FrittståendeTrapp navnes om til Trapp
* Dam navnes om til Demning
* Gondol, Skitrekk og Stolheis utgår som egen objekttype. Alle disse dataene kodes som objekttype Taubane med forskjellige verdier av kodelista taubanetype
* Taubanemast innført som ny objekttype siden det er krav om registrering av disse i NRL. Tidligere var mastene bare registrert som punkter i Taubane-kurvene. Det er modellert inn en assosiasjon fra Taubane til de tilhørende mastene.
* Objekttype Steingjerde og AnnetGjerde slås sammen til objekttypen Gjerde, med egenskapen gjerdetype.
* VeggFrittstående flyttet fra FKB-BygnAnlegg til FKB-Bygning
* Objekttype Navigasjonsinstallasjon flyttet fra FKB-Vann til FKB-BygnAnlegg
* Ny objekttype Parkdetalj og kodeliste Parkdetaljtype. Dekker tidligere objekttype BautaStatue og Sandkasse og i tillegg andre typer innretninger som basseng/fontener og lekeapparater i parker.
* Objekttype Ruin og Avfallsbeholder innført
* Innført egenskapene nvdbpeker, nrlpeker, havnedatapeker, eksternpeker for å gjøre det mulig å legge inn referanser (i form av URI-er) til de tilsvarende objektene forvaltet i andre systemer.
* Egenskapene medium og høydereferanse endret fra opsjonell til påkrevd på en rekke objekttyper. Disse egenskapene er nå alltid angitt som påkrevde der de benyttes (kodes med ukjent-verdi og nødvendig).


=== Normative referanser

include::../felles_prodspek/kap14_normativ_ref.adoc[]

<<<

== Definisjoner og forkortelser

=== Definisjoner

include::../felles_prodspek/kap21_definisjoner.adoc[]

=== Forkortelser

include::../felles_prodspek/kap22_forkortelser.adoc[]

<<<

== Generelt om spesifikasjonen

=== Unik identifisering
FKBBygnAnlegg

==== Fullstendig navn
{datasett} 

==== Versjon
{versjon}

=== Referansedato
{underversjon}

=== Ansvarlig organisasjon
Geovekst

=== Språk
nor

=== Hovedtema
Basisdata, bygningsmessige anlegg, konstruksjoner

=== Temakategori
basisData

=== Sammendrag
FKB-BygnAnlegg beskriver bygningsmessige anlegg som ikke er spesifisert i andre fagspesifikke FKB-datasett som FKB-Bygning eller FKB-Veg. Dette inkluderer objekter som murer, gjerder, kaier, moloer, tanker etc.

=== Formål

include::../felles_prodspek/kap38_formal.adoc[]

FKB-BygnAnlegg er viktig for å gi et komplett bilde av den detaljerte situasjonen i terrenget i forbindelse med f.eks. planlegging og prosjektering.

// Fellesdel som dekker kap 3.9 - 3.12 for alle FKB-produktspesifikasjoner
include::../felles_prodspek/kap39-312_representasjon.adoc[]

=== Supplerende beskrivelse
Data ikke angitt

<<<

== Spesifikasjonsomfang

// Fellesdel
include::../felles_prodspek/kap4_omfang.adoc[]  

<<<

== Innhold og struktur

=== Omfang
<<HeleDatasettet,Hele datasettet>>

include::modellRapport.adoc[]

<<<

== Referansesystem

Romlige referansesystem for håndteres likt for alle FKB-datasett. Se https://sosi.geonorge.no/Standarder/FKB_generell_del/#_romlige_referansesystem[Vedlegg B i FKB Generell del] for en beskrivelse.

<<<

== Kvalitet

include::../felles_prodspek/kap7_kvalitet.adoc[]

<<<

== Datafangst

// Fellesdel
include::../felles_prodspek/kap8_datafangst.adoc[]

<<<

== Datavedlikehold

include::../felles_prodspek/kap9_vedlikehold.adoc[]

<<<

== Presentasjon

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Referanse til presentasjonskatalog
Presentasjonsregler for FKB-data er angitt i skjermkartografispesifikasjonen: https://register.geonorge.no/register/versjoner/tegneregler/geovekst/fkb-skjermkartografi 

<<<

== Leveranse

include::../felles_prodspek/kap11_leveranse.adoc[]

<<<

== Tilleggsinformasjon
Ingen angitt informasjon

== Metadata

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Metadataspesifikasjon

include::../felles_prodspek/kap13_metadata.adoc[]

<<<

[appendix]
== SOSI-format-realisering

SOSI-realiseringen følger kravene i "Realisering i SOSI-format 5.0" <<SOSI-FORMAT>>. Under en utlisting av SOSI-formatrealiseringen:

include::SOSIformatRealisering.adoc[]


[appendix]
== GML-realisering

GML-realiseringen følger kravene i "Realisering i GML-format 5.0" <<SOSI-GML>>. Realiseringen defineres av følgende filer:

* link:{skjema-url}/FKBBygnAnlegg.xsd[GML-skjema]
* link:{skjema-url}/FKBBygnAnlegg.sch[Schematron-regler til validering av tilleggskrav til datainnhold og -struktur utover det som er definert i GML-skjemafil] (sch-fil)
* link:{skjema-url}/eksempel/[Katalog med eksempelfiler]



:sectnums!:

<<<

[discrete]
== Lisensvilkår

// Inkluder lisensvilkår
include::../felles_prodspek/lisensvilkaar.adoc[]
